// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOFyw_WkkfcPNzaEPmMC4GrBBbLk4zG9Q',
    appId: '1:828253710512:web:4a0904d1a0b7cdba2bf375',
    messagingSenderId: '828253710512',
    projectId: 'mi-chatbot-30d81',
    authDomain: 'mi-chatbot-30d81.firebaseapp.com',
    storageBucket: 'mi-chatbot-30d81.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0vUD8pJMYkthH1p8An_9mE92AhMJk_WM',
    appId: '1:828253710512:android:e1e880ca3207cbba2bf375',
    messagingSenderId: '828253710512',
    projectId: 'mi-chatbot-30d81',
    storageBucket: 'mi-chatbot-30d81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3at6oltfr9N1t50cmmD5mwr7SwHnNjvQ',
    appId: '1:828253710512:ios:82411e2dc27e9d662bf375',
    messagingSenderId: '828253710512',
    projectId: 'mi-chatbot-30d81',
    storageBucket: 'mi-chatbot-30d81.appspot.com',
    iosClientId: '828253710512-urrpd31mq1gs6gd2aha2smr2iunubcn6.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3at6oltfr9N1t50cmmD5mwr7SwHnNjvQ',
    appId: '1:828253710512:ios:82411e2dc27e9d662bf375',
    messagingSenderId: '828253710512',
    projectId: 'mi-chatbot-30d81',
    storageBucket: 'mi-chatbot-30d81.appspot.com',
    iosClientId: '828253710512-urrpd31mq1gs6gd2aha2smr2iunubcn6.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboardApp',
  );
}
